image: barichello/godot-ci:3.2.3

# Cache imported assets between runs
#cache:
# key: import-assets
#  paths:
#    - .import/

stages:
  - tests
  - export
    #  - deploy

variables:
  EXPORT_NAME: flock_of_ducks


unitTests:
        stage: tests
        script:
                #- cd Godot/Project
                - godot -s addons/gut/gut_cmdln.gd -d --path $PWD -ginclude_subdirs -gdir=res://test -gexit -gprefix=test_

web:
    stage: export
    script:
        - mkdir -v -p build/web
        - godot -v --export "HTML5" ./build/web/index.html
    artifacts:
        name: $EXPORT_NAME-$CI_JOB_NAME
        paths:
            - build/web

pages:
    stage: deploy
    dependencies:
        - web
    script:
        - rm -rf public
        - cp -r build/web public
    artifacts:
        paths:
            - public
    only:
        - develop
